### ISSUE TITLE
Imagemagic

### ISSUE THREAD

**Issue by towrig** [Myseolumic/praktikaportaal#13]
Otsida ja realiseerida mingi image magic teek.

**Comment by towrig** [comment]
Imagick extension on installitud, peaks olema võimalik nüüd rakendada.

**Comment by kaitkrull** [comment]
https://www.php.net/manual/en/imagick.cropimage.php, ehk on sellest abi?

**Comment by kaitkrull** [comment]
Proovin implementeerida CropperJS (https://github.com/fengyuanchen/cropperjs/blob/v2/README.md) ja Dragzone.js (https://www.dropzonejs.com/). Võimalik, et jätab imagemagicku üldse välja.

**Comment by kaitkrull** [comment]
Commit 9051732 sisaldab osa crop funktsionaalsust. Esmalt sai proovitud lahendada Dragzone.js koostöös failihaldust, kuid hiljem tegin siiski ümber input jaoks. Võiks toimida. Siiski üle tuleb vaadata API poolt tagastavad response sõnumid, et need oleks piisavalt mõistlikud ning kasutajale arukat tagasiside annaks.

**Comment by towrig** [comment]
Crop ei toimi, crashib

**Comment by kaitkrull** [comment]
> Crop ei toimi, crashib

Mis hetkel ta täpsemalt kokku jookseb? Kas siis kui pilt valitud ja kärbitud või kui vormi edastad?

**Comment by towrig** [comment]
> > Crop ei toimi, crashib
> 
> Mis hetkel ta täpsemalt kokku jookseb? Kas siis kui pilt valitud ja kärbitud või kui vormi edastad?

Pmst üritasin viimasena pilti lisada ja kärbi nupp crashis plugina

**Comment by kaitkrull** [comment]
Võime vist selle sulgeda?
