### ISSUE TITLE
Arhiveerimine

### ISSUE THREAD

**Issue by towrig** [Myseolumic/praktikaportaal#22]
Tekstiväljad: 
- Pealkiri (automaatselt andmebaasist vastavalt id-le)
- Kirjeldus
- Tulemus

**Comment by towrig** [comment]
**Arhiveerides alles jätta väljad:**
- Esitaja
- Asutus

Arhiveeritud projekte kuvada **"Projektipraktika"** alamlehel nimega **"Lõppenud projektid"** (teha tabide süsteem).

**Comment by kaitkrull** [comment]
![image](https://user-images.githubusercontent.com/19776899/76625809-b1970c00-6540-11ea-8780-2a5284635132.png)
