### ISSUE TITLE
Praktikapakkumise lisamine failina

### ISSUE THREAD

**Issue by merilyheinalo** [Myseolumic/praktikaportaal#24]
Tööandja peab saama praktikapakkumise lisada ka failina. Selleks täidab ta sarnase vormi nagu projekti lisamisel, kuhu ta lisab:
- kuulutuse pealkiri
- organisatsioon
- registreerimise lõpptähtaeg
- kontaktisiku nimi
- kontaktisiku telefoninumber
- asukoht
- organisatsiooni tutvustus 
- praktika valdkond (saab dropdown menüüst valida)

Pakkumise lisamisel failina peab eelvaates kuvama neid samu asju mis kuvab pakkumistel, mis on keskkonda vormi täites lisatud.

**Comment by kaitkrull** [comment]
@merilyheinalo Kas kokkuvõttes peaks tulema olemasolevale vormile juurde kaks uut "kasti"? Praktika valdkond (mille sisendit siis oleks vaja) ja lisaks sarnane PDF lisamise nupp nagu on teistel vormidel?

**Comment by merilyheinalo** [comment]
Jah, täpselt nii. Praktika valdkonna sisendi koostamisega ma tegelen.

**Comment by towrig** [comment]
Lisaks sellele tuleb muuta eksisteerivat vormi järgnevalt: 
**Kustutada**
- kontaktisiku telefoninumber 

**Kokku võiks panna** 
-  töökoha tutvustus
-  tööülesanded
-  vajalikud oskused ja kogemused 

Kokku pandavatele tulbale nimeks Praktikale nõudmised (nimi veel selgumisel)

**Comment by towrig** [comment]
Vormi muudatused: https://docs.google.com/document/d/14MAvCtZoMp9r4N1sjwG65-M-W-v2eCjdGA33x_0Nev8/edit?usp=sharing
