### ISSUE TITLE
Praktikapakkumiste sorteerimine

### ISSUE THREAD

**Issue by merilyheinalo** [Myseolumic/praktikaportaal#28]
Praktikapakkumiste alamlehel sorteerimise valikute võimaldamine valdkonna ja asukoha järgi.

**Comment by towrig** [comment]
Asukoha genereerin siis vastavalt sisestatutele?

**Comment by merilyheinalo** [comment]
Kas me anname asukoha võimalused ette või kui ta hakkab ise kirjutama siis kuvab talle vastavalt tähtede järgi neid mida on sisestatud?
