### ISSUE TITLE
Esilehel meiega liitunud organisatsioonid numbrite korrektuur

### ISSUE THREAD

**Issue by merilyheinalo** [Myseolumic/praktikaportaal#30]
Kui ühe organisatsiooni alt on mitu pakkumist, siis need peaks kokku andma ikka ühe organisatsiooni. Praegu näitab et organisatsioone on 8, aga tegelt ühe alt on mitu pakkumist lihtsalt. Seega organisatsioone ei ole 8.

**Comment by kaitkrull** [comment]
@merilyheinalo Ootame sinult siis uut ja haaravat nime siia.

**Comment by kaitkrull** [comment]
Kuna nime ei tule, siis sulgen selle.
