### ISSUE TITLE
Luua functions.php

### ISSUE THREAD

**Issue by towrig** [Myseolumic/praktikaportaal#37]
Sinna liigutada funktsioonid:
- truncate

List veel täieneb

**Comment by kaitkrull** [comment]
Palun testi seda viimast 9419ee1 commiti eelnevalt kindlasti!

**Comment by towrig** [comment]
tõmbasin devi külge

**Comment by kaitkrull** [comment]
Tundub, et midagi katki nagu ei läinud. Seega võid ka live vist külge haarata.
