### ISSUE TITLE
Kohtade arv projektis

### ISSUE THREAD

**Issue by towrig** [Myseolumic/praktikaportaal#9]
1. Kuvab palju alles on.
2. Keelab registreerimise kui on täis.

**Comment by towrig** [comment]
Kus tuleks limiiti realiseerida, ehk kus pannakse blokk ette, kas aktiveerimisel või registreerimisel?

**Comment by kaitkrull** [comment]
Ma mõtlen, et kas on võimalik, et kanditaate saab vahetada juhul kui registreerib keegi pädevam? Seega sellisel juhul vist ei peaks limiiti enne tekkima kui registreerimise tähtaeg kukub. Ja siis pärast tähtaeg selekteerib admin välja, keda ta oma tiimi soovib saada. Või peaks see olema siiski kes-ees-see-mees süsteem?

**Comment by towrig** [comment]
Maksimaalne osalejate arv: 10
Minimaalne: 3
Limiit rakendub kinnitamise ajal.
